scalar Date

type Query {
  orders: [Order!]!

  ordersPerDay: [OrdersPerDay!]!

  pendingOrders: [Order!]!

  orderTotals: OrderTotalsResult!

  messagesPerDay: [MessagesPerDay!]!
}

type Mutation {
  login: String
}

type MessagesPerDay {
  day: Date!
  residents: Int
  contacts: Int
  messages: Int
  avgMsgResident: Int
  avgMsgContact: Int
}

type OrdersPerDay {
  day: Date!
  status: String!
  count: Int!
}

type Order {
  id: ID!
  number: String!
  contactId: ID
  inmateId: ID
  recipientInmateId: ID
  createdAt: Date!
  updatedAt: Date,
  status: String!
  items: [OrderItem!]!
  fees: [Fee!]!
  total: Float!
}

type OrderItem {
  id: ID!
  productName: String!
  variantName: String!
  price: Float!
}

type OrderTotalsResult {
  totalGross: Float!
  totals: [ OrdersTotal ]
}

type OrdersTotal {
  type: String!
  total: Float!
}

type Fee {
  id: ID!
  type: String!
  amount: Float!
}
