scalar Date

type Query {
  orders: [Order!]!

  ordersPerDay: [OrdersPerDay!]!

  messagesPerDay: [MessagesPerDay!]!
}

type Mutation {
  login: String
}

type MessagesPerDay {
  day: Date!
  residents: Int
  contacts: Int
  messages: Int
  avgMsgResident: Int
  avgMsgContact: Int
}

type OrdersPerDay {
  date: Date!
  status: String
  count: Int
}

type Order {
  id: ID!
  contactId: ID
  inmateId: ID
  recipientInmateId: ID
  createdAt: Date!
  updatedAt: Date,
  status: String!
}

